services:
  postgres:
    platform: linux/amd64
    image: postgis/postgis:18-3.6
    container_name: turfbuilder_postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=postgres
      - TZ=${TZ}
    shm_size: 128mb
    networks:
      - turfbuilder
    restart: ${RESTART_POLICY}

  frontend:
    container_name: turfbuilder_app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:db_password@postgres:5432/postgres
      - BETTER_AUTH_SECRET=ODiDH4PwSD2KxDoVu7jVfkxooICq5m1P # DO NOT USE IN PRODUCTION! THIS SECRET IS PUBLIC AND ONLY FOR DEV USE!
      - BETTER_AUTH_URL=http://localhost:3000
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    depends_on:
      - postgres
    networks:
      - turfbuilder
    restart: unless-stopped
  frontend-dev:
    container_name: turfbuilder_app_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:db_password@postgres:5432/postgres
      - BETTER_AUTH_SECRET=ODiDH4PwSD2KxDoVu7jVfkxooICq5m1P # DO NOT USE IN PRODUCTION! THIS SECRET IS PUBLIC AND ONLY FOR DEV USE!
      - BETTER_AUTH_URL=http://localhost:5173
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - turfbuilder
    restart: unless-stopped

  nats:
    image: nats:2.10
    container_name: nats-turfbuilder
    restart: unless-stopped
    command: [
      "-js",
      "-m", "8222",
      "--store_dir", "/data/jetstream"
    ]
    ports:
      - "4222:4222"   # client connections
      - "8222:8222"   # monitoring
    volumes:
      - nats_data:/data/jetstream
    networks:
      - turfbuilder
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:latest
    environment:
      - SPAN_STORAGE_TYPE=memory
      - METRICS_STORAGE_TYPE=prometheus
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - turfbuilder
volumes:
  postgres_data:
  nats_data:
networks:
  turfbuilder:
    driver: bridge