name: turfbuilder-e2e
services:
  postgres:
    platform: linux/amd64
    image: postgis/postgis:18-3.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=postgres
      - TZ=${TZ}
    shm_size: 128mb
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s
    networks:
      - turfbuilder
    restart: ${RESTART_POLICY}

  #frontend:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #    target: production
  #  ports:
  #    - '3000:3000'
  #  environment:
  #    - NODE_ENV=production
  #    - DATABASE_URL=postgres://postgres:db_password@postgres:5432/postgres
  #    - BETTER_AUTH_SECRET=ODiDH4PwSD2KxDoVu7jVfkxooICq5m1P # DO NOT USE IN PRODUCTION! THIS SECRET IS PUBLIC AND ONLY FOR DEV USE!
  #    - BETTER_AUTH_URL=http://localhost:3000
  #    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    # volumes:
    #   - .:/app
    #   - /app/node_modules
  #  depends_on:
  #    - postgres
  #  networks:
  #    - turfbuilder
  #  restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - DOCKER=true
      - DATABASE_URL=postgres://postgres:db_password@postgres:5432/postgres
      - BETTER_AUTH_SECRET=ODiDH4PwSD2KxDoVu7jVfkxooICq5m1P # DO NOT USE IN PRODUCTION! THIS SECRET IS PUBLIC AND ONLY FOR DEV USE!
      - BETTER_AUTH_URL=http://localhost:5173
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: sh -c "npm install && npm run dev:nohmr -- --host 0.0.0.0"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - turfbuilder
    restart: unless-stopped

  nats:
    image: nats:2.10
    restart: unless-stopped
    command: [
      "-js",
      "-m", "8222",
      "--store_dir", "/data/jetstream"
    ]
    ports:
      - "4222:4222"   # client connections
      - "8222:8222"   # monitoring
    networks:
      - turfbuilder

networks:
  turfbuilder:
    driver: bridge