import type { ColumnDefinitions, MigrationBuilder } from 'node-pg-migrate';

export const shorthands: ColumnDefinitions | undefined = undefined;

export async function up(pgm: MigrationBuilder): Promise<void> {
    if (process.env.NODE_ENV !== 'development') { return; }   // Ignore me in production!

    // Create a fake superuser
    pgm.sql(`
        INSERT INTO auth."user"
        (
            id, 
            "name", 
            username, 
            display_username, 
            email, 
            email_verified, 
            image, 
            two_factor_enabled, 
            "role", 
            banned, 
            ban_reason, 
            ban_expires, 
            impersonated_by
        ) VALUES(
            'bf2ae2f9-a2db-4516-9c52-3510cfa8f50c'::uuid, 
            'Superuser', 
            'admin', 
            'Admin', 
            'admin@root.com', 
            true, 
            NULL, 
            false, 
            'admin', 
            false, 
            NULL, 
            NULL, 
            NULL
        );
        INSERT INTO auth.account (id, user_id, account_id, provider_id, access_token, refresh_token, access_token_expires_at, refresh_token_expires_at, "scope", id_token, "password", created_at, updated_at) VALUES('fb4bca38-cbb9-4d89-bf03-a93d34ee7b2f'::uuid, 'bf2ae2f9-a2db-4516-9c52-3510cfa8f50c'::uuid, 'c02e537c-8088-4ded-9921-9a2e0b906385', 'credential', NULL, NULL, NULL, NULL, NULL, NULL, '1362c96c1412f019d163628166429a18:0393f2ca4c33e193cfc9334f6f7e8b0f2b7e8496a89bc52ead51787fafacbe2d8dd71ee09def48d86c036d39921e9b007426ced68378928e82857331a769956a', '2026-02-04 23:21:57.746', '2026-02-04 23:21:57.746');
    `);

    // Create a dummy survey
    pgm.sql(
        `INSERT INTO public.survey
            (id, "name", description)
            VALUES('16c94ebc-d422-4769-9beb-deb03a8dfbe3'::uuid, 'Example Survey 1', 'This is an example generated by a dev tool. This is not a real survey that should be used.');`
    )

    // Add survey questions
    pgm.sql(`
        INSERT INTO public.survey_question
        (id, survey_id, question_text, question_type, order_index, choices, created_at, updated_at)
        VALUES('74872073-da3d-418e-8c5d-bc2287c2d505'::uuid, '16c94ebc-d422-4769-9beb-deb03a8dfbe3'::uuid, 'Do you support the <cause> we are canvassing for?', 'radio', 0, '{Yes,No}', '2026-02-04 17:34:26.886', '2026-02-04 17:34:26.886');
        INSERT INTO public.survey_question
        (id, survey_id, question_text, question_type, order_index, choices, created_at, updated_at)
        VALUES('637f8ff6-a6ee-494c-9cf4-de02249f16ef'::uuid, '16c94ebc-d422-4769-9beb-deb03a8dfbe3'::uuid, 'What is your opinion on the current state of affairs?', 'text', 1, '{}', '2026-02-04 17:36:32.564', '2026-02-04 17:36:32.564');
        INSERT INTO public.survey_question
        (id, survey_id, question_text, question_type, order_index, choices, created_at, updated_at)
        VALUES('14e4a5ce-7f63-4caa-b9f5-a377210ebb0b'::uuid, '16c94ebc-d422-4769-9beb-deb03a8dfbe3'::uuid, 'What reasons are you inclined to support our cause?', 'check', 2, '{"I like you","Tired and looking for a change","I think things need more cowbell"}', '2026-02-04 17:36:32.589', '2026-02-04 17:36:32.589');
    `);

}

export async function down(pgm: MigrationBuilder): Promise<void> {}
